In [3]:
import matplotlib.pyplot as plt
import pandas as pd
import numpy as np
import requests
import time

#file to load
api_pulls = "Resources/api_pulls.csv"

pull_data = pd.read_csv(api_pulls)
pull_data.head()

,Formal_Name,Label_Name,2017_Variable,2016_Variable,2015_Variable,2014_Variable,2013_Variable
0,Estimate!!HOUSEHOLDS BY TYPE!!Total households,Households,DP02_0001E,DP02_0001E,DP02_0001E,DP02_0001E,DP02_0001E
1,Estimate!!HOUSEHOLDS BY TYPE!!Total households...,Households (Family),DP02_0002E,DP02_0002E,DP02_0002E,DP02_0002E,DP02_0002E
2,Estimate!!SCHOOL ENROLLMENT!!Population 3 year...,Number of Higher Ed Enrolled,DP02_0057E,DP02_0057E,DP02_0057E,DP02_0057E,DP02_0057E
3,Estimate!!EDUCATIONAL ATTAINMENT!!Population 2...,Education of Some College - No Degree Attained,DP02_0062E,DP02_0062E,DP02_0062E,DP02_0062E,DP02_0062E
4,Estimate!!EDUCATIONAL ATTAINMENT!!Population 2...,Education of Associate's Degree Attained,DP02_0063E,DP02_0063E,DP02_0063E,DP02_0063E,DP02_0063E

In [ ]:
base_url = "https://api.census.gov/data/"
counter = 0
data_year = []
data_acronym = []


url = base_url + data_year[counter] + "/" + data_acronym[counter]